FROM jdzw2014/python:3.8.5

ARG PIP=/usr/local/bin/pip

# install python package
#RUN $PIP install -i https://pypi.tuna.tsinghua.edu.cn/simple --default-timeout=100 botbuilder-core>=4.7.0
#RUN $PIP install  botbuilder-core>=4.7.0

